<h1>About Dirt Cheap Beds</h1>
<p>In 1999 we established the first online bed superstore www.bedworld.net selling brand name beds and mattresses. Over the past ten years we have sold over 500,000 units.

Due to the large number of products sold we now have hundreds of beds and mattresses with slight imperfections to be sold at dirt cheap prices.
They may be ex-display, slightly damaged or returned products but sleeping ability will not be affected so if you can live with a few imperfections you could save yourself a lot of money.
</p>
<p><h2><b>Visit our warehouse at wood street Castleford and pick up a bargain.<font color = red> But Hurry first come first serve,</font></b></h2></p>
