<div id="main">
	<h1>How to contact Dirt Cheap Beds</h1>
	<h2>Live Chat</h2>
	9am til late Every Day
	
	<h2>Emails will normally be answered within 24 hours.</h2>
	
	<h2>Bed Sales Enquiries</h2> <h3>(Monday-Friday 9am - 5pm)</h3>  <h3>Saturday 10am - 4pm - Sales Only</h3>
	
	<p>If you need to contact our sales team for any reason drop us an email at sales@bedworld.net. If you have seen a bed cheaper elsewhere, want to ask about a product, or enquire about special sizes; our sales team is on standby and ready to answer your questions on 0845 8339223.<br />  (Monday- Friday 9 - 10pm).-  Saturday 10am - 4pm - Sales Only</p>
	
	
	<h2>Customer Care / After Sales</h2> <h3>Mon - Friday 9am til 5pm</h3>
	<p>If you have any questions about your order please contact our customer care department by email at customercare@bedworld.net</p>
	
	
	<h2>Deliveries</h2> <h3>Mon - Friday 9am til 5pm</h3>
	<p>For enquiries about deliveries contact our delivery department by email at deliveries@bedworld.net</p>
	
	
	<h2>Technical Department</h2> <h3>Mon - Friday 9am til 5pm</h3>
	<p>If you have any questions, comments, or suggestions regarding our website please feel free to contact webteam@bedworld.net.</p>
	
	
	<h2>Head office address</h2>  <h3>Mon - Friday 9am til 5pm</h3>
	<p>If you have any questions, comments, or suggestions regarding our website please feel free to contact Bedworld by post at
	Bedworld Calder House Savile Road Castleford WF10 1BJ</p>
	
	
	<h2>Registered office address</h2>
	<p>Langwood House 63 - 81 High Street Rickmansworth London. Herts. WD3 1EQ</p>
	
	
	<h2>New Suppliers.</h2>
	<p>If you are wanting to supply your company products to Bedworld please use the following contact. newsuppliers@bedworld.net</p>
</div>