<div id="main">
	<h1>Delivery Information</h1>
	<p>Due to our dirt cheap prices we offer a delivery service charged for by distance.</p>
<p>Many beds are boxed and suitable for Cash and Carry - We also have a very large selection of vacuum packed rolled up Memory Foam Mattresses suitable to transport by car.</p>
	<ul>
		<li>
			<h2>Next Day Delivery</h2>
			<ul>
				<li> Selected Items will be delivered within 24hrs if ordered is placed before 3pm.</li>
			
			</ul>
		</li>
		<li>
			<h2>Three Day Delivery</h2>
			<ul>
				<li>Selected Items will be delivered 3 days from order date.</li>
				
			</ul>
		</li>
	
		<li>
			<h2>Saturday Delivery Available</h2>
			
		</li>
	</ul>
</div>