<div class="content">
	<div class="float-left">
		<img src="/images/discounted-content.gif" alt="Discounted Beds &amp; Mattresses" class="discount" width="312" height="56"/>
		<h1>Dirt Cheap Beds Warehouse</h1>
		<p>Come visit our new 50,000sqft warehouse in Castleford full of clearance mattresses, metal beds, wooden beds, leather beds, bunk beds, Sofa beds, Futons and memory foam mattresses all at dirt cheap prices.</p>
		<p>They may be ex-display, slightly damaged or returned products but sleeping ability will not be affected so if you can live with a few imperfections you could save yourself  a lot of money.</p>
<p>Dirt cheap beds clearence warehouse full of low price Bargain beds and Discounted mattresses. View the largest selection of brand name cheap beds online at Bedworld.net</p>
		<p><b>Open to the Public, Landlords, Trade auctioneers, bed retailers, Job lots, Market Traders, Wholesale and eBay resellers. All goods are new and sold as seen and  our huge stock holding changes daily.</b></p>
		<h2 class="red"> Leather Sofa beds From &pound;169.00</h2>
		<h3>Free parking</h3> 
		<p>Cash and Carry - or delivery can be arranged prior to purchase.</p>
	</div>
	<div class="float-left middle">
		<img src="/images/open-now.gif" alt="Open Now" class="open-now" width="128" height="127"/>
		<img src="/images/seek-bargains.gif" alt="We seek bargains so you don't have to" class="seek-bargins" width="179" height="115"/>
	</div>
	<div class="float-left right">
		<a href="/pictures" style="text-decoration:none;display:block;margin-bottom:0;"><img src="/images/location/home-box.jpg" width="375" alt="" /><br /><span style="font: bold 12px Arial,Helvetica,Geneva;color:#000;float:right;margin-right:6px;">View All Pictures</span></a><br />
		<img style="margin:10px 0 0 -1px;" src="/images/to-clear.gif" alt="Over 1000 Leather Beds to Clear" />
	</div>
</div>
<?php include 'includes/boxes.inc';?>