<div id="main">
<p>
	This page (together with the documents referred to on it) tells 
	you the terms and conditions on which we supply any of the goods 
	(Goods) listed on our website www.bedworld.net (our site) to you. 
	Please read these terms and conditions carefully before ordering 
	any Goods from our site. You should understand that by ordering 
	any of our Goods, you agree to be bound by these terms and conditions.
</p>
<p>
	You should print a copy of these terms and conditions for future reference.
</p>
<p>
	Please click on the button marked "I Accept" in our shopping cart if you 
	accept them. Please understand that if you refuse to accept these terms 
	and conditions, you will not be able to order any Goods from our site.
</p>
<div class="terms1">
	<ol class="term">
		<li>
			<h4>INFORMATION ABOUT US</h4>
			<ol>
				<li>
					www.dirtcheapbeds.co.uk is a site 
					operated by Bedworld (North) Limited (we).  We are registered in England 
					and Wales under company number 03145929 and with our registered office 
					at Langwood House 63 &minus; 81 High Street, Rickmansworth, and Herts., WD3 1EQ. 
					Our main trading address is Calder House, Saville Road, Castleford, WF10 1BJ. 
					Our VAT number is [613348164].
				</li>
			</ol>
		</li>
		<li>
			<h4>SERVICE AVAILABILITY</h4>
			<ol>
				<li>
					Our site is only intended for use by people resident in the United Kingdom.  
					We currently do not accept orders from individuals outside those countries.  
				</li>
			</ol>
		</li>
		<li>
			<h4>YOUR STATUS</h4>
				<ol>
					<li>
						By placing an order through our site, you warrant that:
						<ol>
							<li>
								You are legally capable of entering into binding contracts;
							</li>
							<li>
								You are at least 18 years old; and
							</li>
							<li>
								You are resident in the United Kingdom
							</li>
						</ol>
					</li>
				</ol>
		</li>
		<li>
			<h4>HOW THE CONTRACT IS FORMED BETWEEN YOU AND US</h4>
			<ol>
				<li>
					After placing an order, you will receive an e-mail from us 
					acknowledging that we have received your order.  Please note 
					that this does not mean that your order has been accepted.  
					Your order constitutes an offer to us to buy Goods.
				</li>
				<li>
					If the Goods you have ordered are not available or 
					discontinued, or if we are unable to deliver them to you 
					within 60 days, we shall inform you of this. In this event, 
					no Contract shall have been formed between you and us. 
				</li>
				<li>
					If we are unable to supply the Product and payment 
					has already been made by the buyer, then the buyers account 
					will be refunded or re-credited with the sum paid by the Buyer. 
					The Seller will not be obliged to offer any compensation for disappointed suffered.
				</li>
			</ol>
		</li>
		<li>
			<h4>THIRD PARTY SELLERS</h4>
			<ol>
				<li>
					We may provide links on our site to the websites of other companies, 
					whether affiliated with us or not.  We cannot give any undertaking, 
					that goods you purchase from third party sellers through our site, 
					or from companies to whose website we have provided a link on our site, 
					will be of satisfactory quality, and any such warranties are DISCLAIMED 
					by us absolutely.  This DISCLAIMER does not affect your statutory 
					rights against the third party seller.  We will notify you when a 
					third party is involved in a transaction, and we may disclose your 
					customer information related to that transaction to the third party seller.
				</li>
			</ol>
		</li>
		<li>
			<h4>CONSUMER RIGHTS</h4>
			<ol>
				<li>
					If you are contracting as a consumer, you may cancel a Contract 
					at any time within seven working days, beginning on the day after you 
					received the Goods.  In this case, you will receive a full refund 
					of the price paid for the Goods in accordance with our refunds policy 
					(set out in Clause 10 below).
				</li>
				<li>
					To cancel a Contract, you must inform us in writing.  You must make 
					the Goods available to us for collection and during this time keep the 
					Goods in the same condition in which you received them.  You may not 
					use the Goods. You have a legal obligation to take reasonable care of 
					the Goods while they are in your possession.  If you fail to comply 
					with this obligation, we may have a right of action against you for compensation.
				</li>
				<li>
					If a customer wishes to cancel after receiving goods, for reasons of 
					change of mind, incorrect goods ordered, wrong size, wrong colour choice, 
					do not fit for any reason, then there is a &pound;49 administration and collection fee. 
				</li>
				<li>
					You will not have any right to cancel a Contract for the supply of 
					any Goods that were made to your explicit specifications or which have 
					been clearly personalised for your use.
				</li>
				<li>
					If you have entered into an agreement under which fixed sum credit 
					is granted by us (or by another person under an arrangement between 
					that person and us) to fully or partly pay the Contract price 
					("Related Credit Agreement"), then your notice to cancel the Contract 
					will also cancel the Related Credit Agreement.
				</li>
				<li>
					Please be aware that images of our products on our website are for 
					illustration purposes only.  Any item that is not a bed or the specified 
					product in the product description on the web page, or that appears in 
					any photograph or illustration on the website will not form part of this 
					contract. An example of such things are lamps, bed covers, pictures 
					and in certain instances headboards (unless previously mentioned in 
					product description). 
				</li>
			</ol>
		</li>
		<li>
			<h4>RISK AND TITLE</h4>
			<ol>
				<li>
					The Goods will be at your risk from the time of delivery pursuant 
					to clause 9 and if you wrongfully fail to take delivery of the Goods, 
					then risk of the Goods shall pass to you at the time we tendered delivery of the Goods.
				</li>
				<li>
					Ownership of the Goods will only pass to you when we receive full 
					payment of all sums due in respect of the Goods, including any delivery charges.
				</li>
			</ol>
		</li>
		<li>
			<h4>PRICE AND PAYMENT</h4>
			<ol>
				<li>
					The price of any Goods will be as quoted on our site from time to time, 
					except in cases of obvious error.
				</li>
				<li>
					These prices include VAT but exclude delivery costs, which will be added 
					to the total amount due as set out in our Delivery Guide. Prices are 
					liable to change at any time, but changes will not affect orders in respect 
					of which we have already sent you an Order Confirmation.
				</li>
				<li>
					Our site contains a large number of Goods and it is always possible that, 
					despite our best efforts, some of the Goods listed on our site may be 
					incorrectly priced.  We will normally verify prices as part of our dispatch 
					procedures so that, where correct price is less than our stated price; 
					we will charge the lower amount when dispatching the Goods to you.  If a 
					correct price is higher than the price stated on our site, we will normally, 
					at our discretion, either contact you for instructions before dispatching the 
					Goods, or reject your order and notify you of such rejection.
				</li>
				<li>
					We are under no obligation to provide the Goods to you at the incorrect 
					(lower) price, even after we have sent you an Order Confirmation, if the 
					pricing error is obvious and unmistakeable and could have reasonably been 
					recognised by you as a mis-price.
				</li>
				<li>
					Payment for all Goods must be by credit or debit card. We accept payment 
					made with all major credit/debit cards, with the exception of American 
					Express. Your credit or debit card will be charged at the time the order is made.
				</li>
			</ol>
		</li>
		<li>
			<h4>DELIVERY</h4>
			<ol>
				<li>
					<span class="bold">Next Day Delivery Items</span> - When you order a next day 
					product you have an option to choose your delivery date. Goods will be 
					delivered on the date chosen; delivery times are between 8:30am and 5:30pm. 
					Unfortunately we are unable to give a more accurate delivery time on our next 
					day delivery products. If you reside in an apartment or a block of flats, the 
					delivery driver will deliver to the lobby of the building only. Please be aware 
					that this service is a one man delivery only.
				</li>
				<li>
					On all next day deliveries items, certain postcodes can not be guaranteed 
					on a next day delivery service and may take up to three days. These are as 
					follows: <span class="bold">AB, IV, PA, KW, and PH</span>. 
				</li>
				<li>	
					If your order consists of a bed frame and a mattress these may be delivered 
					at seperate times and on seperate vehicles. This can be due to the goods 
					being dispatched from seperate depots. 
				</li>
				<li>	
					Please understand that the delivery company that offer a 'next day' 
					service are not insured to enter private premises. Please be aware that 
					if you purchase a mattress on a 'next day' delivery and require assistance 
					with the positioning of the product, you must arrange the assistance yourself. 
				</li>
				<li>	
					Unfortunately we do not deliver to any off shore Islands. We only deliver to mainland Britain. 
				</li>
				<li>	
					<span class="bold">Three Day Delivery Items</span> - When you order a 3 Day 
					delivery product you will be contacted within three working days to confirm a 
					suitable delivery date. If you reside in an apartment or a block of flats, 
					the delivery driver will deliver to the lobby of the building only. 
				</li>
				<li>	
					<span class="bold">In Stock Items</span> - When you order an In Stock item, 
					the delivery lead time is approximately 5-10 working days. You will be 
					contacted within this time to arrange a suitable delivery date and time. 
				</li>
				<li>	
					<span class="bold">Normal Deliveries</span> - Normal deliveries relate to 
					products which have to be ordered from the manufacturers. These are subject 
					to the manufacturer lead times as stated on our website. You will be 
					contacted within this lead time to arrange suitable delivery date and 
					times. Lead times are estimates only and may vary. 
				</li>
				<li>	
					<span class="bold">Saturday Deliveries</span> - Saturday deliveries are 
					available on selected products only at a charge of &pound;15.00 Delivery time 
					for a Saturday delivery time is between 8:30am and 1.00pm. If you reside 
					in an apartment or a block of flats, the delivery driver will deliver 
					to the lobby of the building only. Please note this service is a one 
					man delivery only.
				</li>
				<li>	
					Your order will be fulfilled by the delivery date set out in the Order 
					Confirmation or, if no delivery date is specified, then within 60 days 
					of the date of the Order Confirmation, unless there are exceptional circumstances.
				</li>
				<li>	
					Unless otherwise agreed in writing by You and Us, the delivery of the 
					Goods will take place at the address you have specified in the order 
					(if the Goods are to be delivered to another address other than the 
					registered cardholder's address, proof of address will be required).
				</li>
				<li>	
					Provided that we deliver the Goods to the address you have specified 
					in the order (or any other address agreed by us in writing) then the 
					Goods will be deemed to have been delivered and we will not be liable 
					to you for non-delivery of the Goods. We do not have to satisfy 
					ourselves that the person who accepts delivery at the address you have 
					provided is you (or is a person authorised by you to accept delivery of the Goods).
				</li>
				<li>	
					Any dates and times quoted for delivery of the Goods are approximate only. 
					The Goods may be delivered to you in advance of any estimated delivery time, 
					giving you reasonable written notice.
				</li>
				<li>	
					Goods delivered by us or by a third party contracted to undertake delivery 
					on our behalf are delivered only to the inside of your doorstep. If you 
					request that Goods are taken inside your property, or request any assistance, 
					then we or any third party contractor shall not be liable for any damage to 
					carpets, fixtures, fittings or the structure of your accommodation 
					(e.g. plasterwork, brickwork) that may occur. It is at the customer's risk. 
					Such an action is undertaken solely on your individual responsibility. 
					Please note that any claims for damages arising from the above must be 
					claimed with the buyers own insurance. Bedworld will not be held liable.
				</li>
				<li>	
					Please note that all the above deliveries are subject to good road/weather 
					conditions.  We cannot be held be held responsible for road closures, 
					accidents and adverse weather conditions, that delay your delivery.
				</li>
				<li>	
					When a delivery date has been arranged with the customer and our delivery 
					team arrive and the Buyer is not present to receive delivery, the Seller 
					reserves the right to charge the Buyer a minimum of &pound;29 to cover the cost 
					of the failed delivery.
				</li>
				<li>
					Please note that if you request a call prior to delivery, this cannot be guaranteed. Our delivery times as outlined above. 
				</li>
			</ol>
		</li>
		<li>
			<h4>OUR REFUNDS POLICY</h4>
			<ol>
				<li>
					If you are asking for a refund because you have cancelled the Contract 
					between us within the seven-day cooling-off period (see Clause 6 above) 
					either by email or writing, we will process the refund due to you as 
					soon as possible and, in any case, within 30 days of the day you have 
					given notice of your cancellation and collect the Goods from your 
					premises as soon as practicable. In this case, we will refund the price 
					of the Goods in full, including the cost of delivery to you (if any).  
					However, there is a charge of &pound;49 for the administration and collection fee.
				</li>
				<li>
					For any other reason (for instance, because you have notified us in 
					accordance with paragraph 20 that you do not agree to any change in 
					these terms and conditions or in any of our policies, or because you 
					claim that an item is defective pursuant to clauses 12 below), we 
					will collect the item free of charge as soon as practicable, examine 
					it and notify you of your refund via e-mail within a reasonable 
					period of time. Goods returned by you because of a defect will be 
					refunded in full, including a refund of any delivery charges for 
					sending the item to you and any cost incurred by you in returning 
					the item to us. We will usually process the refund due to you as 
					soon as possible and in any case within 30 days of the day we confirmed 
					to you via e-mail that you were entitled to a refund for the defective Goods.
				</li>
				<li>
					We will usually refund any money received from you using the same 
					method originally used by you to pay for your purchase.
				</li>
			</ol>
		</li>
		<li>
			<h4>CUSTOMER CARE/AFTER SALES</h4>
			<ol>
				<li>
					Please note all after sales queries regarding any issues relating 
					to damage/defects of items received, must be put in writing either 
					by post or email to customercare@bedworld.net.
				</li>
				<li>
					If a product is damaged, in order to identify the damages part 
					correctly, we may request that images are sent in order to resolve 
					the situation quickly and efficiently.
				</li>
				<li>	
					If it is deemed that the damage is due to mis-use, we will not be 
					deemed reliable to replace/repair the damaged item.
				</li>
				<li>	
					Mis-use of bed frames with centre rails and support legs &minus; Please 
					note that purchases of bed frames that have centre rails and support 
					legs there must be a 5mm gap left between the support legs and the 
					floor.  Also, it is recommended that a non slip pad/castor cup is 
					placed under each leg/foot if the bed frame is being placed on a 
					wooden/laminate floor. This is to help prevent the legs from slipping 
					and damaging the centre rail.
				</li>
				<li>	
					If moving a bed frame with support legs, you should lift the 
					frame rather than drag it as the centre support rail and legs 
					will collapse. This will be classed as mis&minus;use and no further 
					action will be taken by Bedworld.
				</li>
			</ol>
		</li>
		<li>
			<h4>OUR LIABILITY</h4>
			<ol>
				<li>
					We warrant to you that Goods purchased from us through our site 
					are of satisfactory quality and reasonably fit for the purpose 
					for which Goods of the kind are commonly supplied.
				</li>
				<li>	
					Our liability for losses you suffer as a result of us breaking 
					this agreement is strictly limited to the purchase price of the 
					Goods and any losses which are a foreseeable consequence of us 
					breaking the agreement.  Losses are foreseeable where they could 
					be contemplated by you and us at the time your order is accepted by us.
				</li>
				<li>	
					This does not include or limit in any way our liability: 
					<ol>
						<li>For death or personal injury caused by our negligence;</li>
						<li>Under section 2(3) of the Consumer Protection Act 1987;</li>
						<li>For fraud or fraudulent misrepresentation; or</li>
						<li>For any matter for which it would be illegal for us to exclude, or attempt to exclude, our liability.</li>
					</ol>
				</li>
				<li>	
					We are not responsible for indirect losses which happen as a side effect 
					of the main loss or damage and which are not foreseeable by you and us 
					(such as loss of income or revenue, loss of business, loss of profits or 
					contracts, loss of anticipated savings, loss of data, waste of management 
					or office time) however arising and whether caused by tort (including 
					negligence), breach of contract or otherwise.
				</li>
			</ol>
		</li>
		<li>
			<h4>WARRANTIES</h4>
			<ol>
				<li>
					We will endeavour to transfer to you the benefit of any manufacturer's warranty or guarantee given to us. 
				</li>
				<li>
					Subject to Clauses 13.3 and 13.4 below, we warrant that the Goods will correspond with their specification at the time of delivery and will be free from defects in quality, material workmanship and condition for a period of 12 months from delivery. 
				</li>
				<li>
					We shall not be liable for a breach of warranty as set out in Clause 13.2, unless
					<ol>
						<li>
							You give us written/email notice of the defect within 7 days of the time you discover the defect.
						</li>
						<li>
							You may be asked to provide images of the defect/damaged goods.
						</li>
					</ol>
				</li>
				<li>	
					We shall not be liable for a breach of the warranty in Clause 13.2
					<ol>
						<li>
							If you make any further use of such Goods after giving notice of the defect to us; or
						</li>
						<li>
							If the defect arises as a result of fair wear and tear, wilful damage, negligence, misuse or your failure to follow our oral or written instructions as to the storage, assembly or use of the Goods; or
						</li>
						<li>
							You alter or repair the Goods without our prior written consent. 
						</li>
					</ol>
				</li>
				<li>
					If any of the Goods do not conform to the warranty, then within 30 days of collecting the defective Goods, we will at our option:
					<ol>
						<li>
							Repair or replace such Goods (or the defective part) free of charge; or
						</li>
						<li>
							Refund the price of such Goods in accordance with clause 10.
						</li>
					</ol>
				</li>
			</ol>
		</li>
		<li>
			<h4>SUSPENSION OF FUTURE DELIVERIES</h4>
			<ol>
				<li>
					We reserve the right to suspend future deliveries of Goods and cancel any Contracts with you and your right to possession of the Goods shall terminate immediately, if you:
					<ol>
						<li>
							Have a bankruptcy order made against you or make an arrangement or composition with your creditors;
						</li>
						<li>
							Convene a meeting of creditors or enter into liquidation (whether voluntary or compulsory), except a solvent voluntary liquidation for the purposes only of reconstruction or amalgamation;
						</li>
						<li>	
							Have a receiver and / or administrator or administrative receiver appointed;
						</li>
						<li>	
							Pass a resolution of is served with a petition for the winding up of or for the granting of an administration order in respect of you;
						</li>
						<li>	
							Have proceedings issued against you in relation to your insolvency or potential insolvency;
						</li>
						<li>	
							Suffer or allow any execution to be levied on your property or obtained against you;
						</li>
						<li>	
							Fail to observe or perform any of your obligations under the Contract or any other contract between us and yourself;
						</li>
						<li>	
							Are unable to pay any debts within the meaning of section 123 of the Insolvency Act 1986;
						</li>
						<li>	
							Cease to trade; or Encumber or in any way charge any of the Goods. 
						</li>
						<li>	
							If we find that any transactions have been placed fraudulently.
						</li>
					</ol>
				</li>
			</ol>
		</li>
		<li>
			<h4>WRITTEN COMMUNICATIONS</h4>
			<ol>
				<li>
					Applicable laws require that some of the information or communications we send to you should be in writing/email.  When using our site, you accept that communication with us will be mainly electronic.  We will contact you by e&minus;mail or provide you with information by posting notices on our website.  For contractual purposes, you agree to this electronic means of communication and you acknowledge that all contracts, notices, information and other communications that we provide to you electronically comply with any legal requirement that such communications be in writing.  This condition does not affect your statutory rights.
				</li>
			</ol>
		</li>
		<li>
			<h4>NOTICES</h4>
			<ol>
				<li>
					All notices given by you to us must be given to Bedworld (North) Limited at Calder House, Saville Road, Castleford, WF10 1BJ or email customercare@bedworld.net.  We may give notice to you at either the e&minus;mail or postal address you provide to us when placing an order, or in any of the ways specified in Clause 14 above.  Notice will be deemed received and properly served immediately when posted on our website, 24 hours after an e&minus;mail is sent, or seven days after the date of posting of any letter.  In proving the service of any notice, it will be sufficient to prove, in the case of a letter, that such letter was properly addressed, stamped and placed in the post and, in the case of an e&minus;mail that such e&minus;mail was sent to the specified e&minus;mail address of the addressee.
				</li>
			</ol>
		</li>
		<li>
			<h4>TRANSFER OF RIGHTS AND OBLIGATIONS</h4>
			<ol>
				<li>
					The Contract between you and us is binding on you and us and on our respective successors and assigns. 
				</li>
				<li>	
					You may not transfer, assign, charge or otherwise dispose of a Contract, or any of your rights or obligations arising under it, without our prior written consent.
				</li>
				<li>	
					We may transfer, assign, charge, sub&minus;contract or otherwise dispose of a Contract, or any of our rights or obligations arising under it, at any time during the term of the Contract.
				</li>
			</ol>
		</li>
		<li>
			<h4>EVENTS OUTSIDE OUR CONTROL</h4>
			<ol>
				<li>
					We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under a Contract that is caused by events outside our reasonable control 
					<br />(Force Majeure Event).
				</li>
				<li>
					A Force Majeure Event includes any act, event, non&minus;happening, omission or accident beyond our reasonable control and includes in particular (without limitation) the following:
					<ol>
						<li>
							Strikes, lock&minus;outs or other industrial action.
						</li>
						<li>	
							Civil commotion, riot, invasion, terrorist attack or threat of terrorist attack, war (whether declared or not) or threat or preparation for war.
						</li>
						<li>	
							Fire, explosion, storm, flood, earthquake, subsidence, epidemic or other natural disaster.
						</li>
						<li>	
							Impossibility of the use of roads, railways, shipping, aircraft, motor transport or other means of public or private transport.
						</li>
						<li>
							Impossibility of the use of public or private telecommunications networks.
						</li>
						<li>	
							The acts, decrees, legislation, regulations or restrictions of any government.
						</li>
					</ol>
				</li>
				<li>
					Our performance under any Contract is deemed to be suspended for the period that the Force Majeure Event continues, and we will have an extension of time for performance for the duration of that period.  We will use our reasonable endeavours to bring the Force Majeure Event to a close or to find a solution by which our obligations under the Contract may be performed despite the Force Majeure Event.
				</li>
			</ol>
		</li>
		<li>
			<h4>WAIVER</h4>
			<ol>
				<li>
					If we fail, at any time during the term of a Contract, to insist upon strict performance of any of your obligations under the Contract or any of these terms and conditions, or if we fail to exercise any of the rights or remedies to which we are entitled under the Contract, this shall not constitute a waiver of such rights or remedies and shall not relieve you from compliance with such obligations.
				</li>
				<li>	
					A waiver by us of any default shall not constitute a waiver of any subsequent default.
				</li>
				<li>	
					No waiver by us of any of these terms and conditions shall be effective unless it is expressly stated to be a waiver and is communicated to you in writing in accordance with Clause 14 above.	
				</li>
			</ol>
		</li>
		<li>
			<h4>SEVERABILITY</h4>
			<ol>
				<li>
					If any of these terms and conditions or any provisions of a Contract are determined by any competent authority to be invalid, unlawful or unenforceable to any extent, such term, condition or provision will to that extent be severed from the remaining terms, conditions and provisions which will continue to be valid to the fullest extent permitted by law
				</li>
			</ol>
		</li>
		<li>
			<h4>ENTIRE AGREEMENT</h4>
			<ol>
				<li>
					These terms and conditions and any document expressly referred to in them represent the entire agreement between us in relation to the subject matter of any Contract and supersede any prior agreement, understanding or arrangement between us, whether oral or in writing.
				</li>
				<li>	
					We each acknowledge that, in entering into a Contract, neither of us has relied on any representation, undertaking or promise given by the other or be implied from anything said or written in negotiations between us prior to such Contract except as expressly stated in these terms and conditions.
				</li>
				<li>	
					Neither of us shall have any remedy in respect of any untrue statement made by the other, whether orally or in writing, prior to the date of any Contract (unless such untrue statement was made fraudulently) and the other party's only remedy shall be for breach of contract as provided in these terms and conditions.
				</li>
				<li>	
					We intend to rely upon these terms and conditions and any document expressly referred to in them in relation to the subject matter of any Contract.  While we accept responsibility for statements and representations made by our duly authorised agents, please make sure you ask for any variations from these terms and conditions to be confirmed in writing.
				</li>
			</ol>
		</li>
		<li>
			<h4>OUR RIGHT TO VARY THESE TERMS AND CONDITIONS</h4>
			<ol>
				<li>
					We have the right to revise and amend these terms and conditions from time to time.
				</li>
				<li>
					You will be subject to the policies and terms and conditions in force at the time that you order Goods from us, unless any change to those policies or these terms and conditions is required to be made by law or governmental authority (in which case it will apply to orders previously placed by you), or if we notify you of the change to those policies or these terms and conditions before we send you the Order Confirmation (in which case we have the right to assume that you have accepted the change to the terms and conditions, unless you notify us to the contrary within seven working days of receipt by you of the Goods).	
				</li>
			</ol>
		</li>
		<li>
			<h4>GENERAL</h4>
			<ol>
				<li>
					We own the copyright in and operate this website. Any photographs displayed on our website have been reproduced by us with the permission of the copyright owner. You may not copy, reproduce, republish, upload, post, transmit or distribute any material from this website in any way without our express written permission. All trade marks, service marks and trade names are our property (or are used with the permission of the trademark owner). Infringement of any copyright or trademarks on this website may lead to legal action against the infringer.
				</li>
			</ol>
		</li>
		<li>
			<h4>PRIVACY AND SECURITY POLICY</h4>
			<ol>
				<li>
					We are registered as Data Controller in accordance with the terms of the Data Protection Act 1998. 
				</li>
				<li>
					You may visit this website and access the public information while remaining anonymous and not revealing any personal information.
				</li>
				<li>
					We may record details of the domains from which users visit this site and analyse the data to assess trends, statistics and customer's needs. Information and data may be automatically collected through cookies. Users should familiarise themselves with the operation of cookies. Most browsers are initially set up to accept cookies. If you prefer you can set yours to refuse cookies.
				</li>
				<li>
					If you wish to make an online purchase from us, then you will be required to provide certain personal information as a prerequisite of being able to place an order. We will only ask you for as much information as we need to process your order and perform the Contract. That information will be:
					<ol>	
						<li>
							Retained by us for as long as it is needed to perform the Contract; and
						</li>
						<li>
							Kept secure in accordance with the requirements of the Data Protection Act 1998.
						</li>
						<li>
							We shall not transfer any of your information outside of the European Economic Union.
						</li>
					</ol>
				</li>
				<li>
					You may contact us at any time for access to your information in order to ensure that the information is correct and up to date.
				</li>
				<li>
					At the time of placing your Order you give your consent to us to contact you by electronic mail in relation to the supply of the Goods.
				</li>
				<li>
					When placing an order you have the opportunity to specifically allow us to provide you with details of products which we consider to be of interest to you by ticking a corresponding box. If you do not give your consent, then we will not send you any such information. If at ant time you wish to withdraw your consent, you should notify us immediately in writing.
				</li>
				<li>
					In accordance with our security policy, we will use all reasonable endeavours to ensure that:
					<ol>
						<li>
							Our ordering system is on a secure server and is encrypted to prevent any security breach;
						</li>
						<li>
							Any information you send to us (personal information or credit card details) is kept secure and cannot be intercepted by a third party; and
						</li>
						<li>
							Any equipment at our business address is kept secure to avoid any tampering or unauthorized use of your information.
						</li>
					</ol>
				</li>
			</ol>
		</li>
		<li>
			<h4>LAW AND JURISDICTION</h4>
			<ol>
				<li>
					Contracts for the purchase of Goods through our site will be governed by English law. Any dispute arising from, or related to, such Contracts shall be subject to the non&minus;exclusive jurisdiction of the courts of England and Wales.
				</li>
			</ol>
		</li>
		<li>
			<h4>PRIVACY POLICY</h4>
				<ol>
					<li>
						In deciding whether to accept your order we may 
						use the information you have given to us, or we already hold about you, or which 
						we receive from any enquiry we may make with
						SagePay, to confirm your identity.
						SagePay will check any details we disclose to them against any 
						data bases (public or private) to which they have access and will keep a record 
						of that check.
					</li>
					<li>
						SagePay will also retain this information and may use it in the 
						future to assist other companies with identity verification. This assists us to 
						protect you and us from fraudulent transactions.
					</li>
					<li>
						In summary We are committed to protecting your privacy. 
						We use the information we collect on the site to make shopping at Bedworld.net 
						possible and to enhance your overall shopping experience. We do not sell, trade 
						or rent your personal information to others. 
					</li>
				</ol>
		</li>
	</ol>
</div>
</div>