<br style="clear:both;"/>
<ul class="boxes">
	<li>
		<h1 id="metal-beds">Metal Beds</h1>
		<img src="/images/metal-bed.gif" alt="Metal Bed" width="190" height="135"/>
		<ul>
			<li><span class="name"><span class="bold">Single</span> Metal Beds</span><span class="from from-29">From &pound;29.00</span></li>
			<li><span class="name"><span class="bold">Small Double</span> Metal Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Double</span> Metal Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Kingsize</span> Metal Beds</span><span class="from from-69">From &pound;69.00</span></li>
			<li><span class="name"><span class="bold">Super Kingsize</span> Metal Beds</span><span class="from from-99">From &pound;99.00</span></li>
		</ul>
	</li>
	<li>
		<h1 id="wooden-beds">Wooden Beds</h1>
		<img src="/images/wooden-bed.gif" alt="Wooden Bed" width="190" height="135"/>
		<ul>
			<li><span class="name"><span class="bold">Single</span> Wooden Beds</span><span class="from from-29">From &pound;29.00</span></li>
			<li><span class="name"><span class="bold">Small Double</span> Wooden Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Double</span> Wooden Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Kingsize</span> Wooden Beds</span><span class="from from-69">From &pound;69.00</span></li>
			<li><span class="name"><span class="bold">Super Kingsize</span> Wooden Beds</span><span class="from from-99">From &pound;99.00</span></li>
		</ul>
	</li>
	<li>
		<h1 id="leather-beds">Leather Beds</h1>
		<img src="/images/leather-bed.gif" alt="Leather Bed" width="190" height="135"/>
		<ul>
			<li><span class="name"><span class="bold">Single</span> Leather Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Small Double</span> Leather Beds</span><span class="from from-99">From &pound;99.00</span></li>
			<li><span class="name"><span class="bold">Double</span> Leather Beds</span><span class="from from-99">From &pound;99.00</span></li>
			<li><span class="name"><span class="bold">Kingsize</span> Leather Beds</span><span class="from from-99">From &pound;99.00</span></li>
			<li><span class="name"><span class="bold">Super Kingsize</span> Leather Beds</span><span class="from from-99">From &pound;99.00</span></li>
		</ul>
	</li>
	<li>
		<h1 id="bunk-beds">Bunk Beds</h1>
		<img src="/images/bunk-bed.gif" alt="Bunk Bed" width="190" height="135"/>
		<ul>
			<li><span class="name"><span class="bold">Wooden</span> Bunk Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Alloy</span> Bunk Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Midi</span> Bunk Beds</span><span class="from from-49">From &pound;49.00</span></li>
			<li><span class="name"><span class="bold">Sofa</span> Bunk Beds</span><span class="from from-99">From &pound;99.00</span></li>
			<li><span class="name"><span class="bold">Studio</span> Bunk Beds</span><span class="from from-99">From &pound;99.00</span></li>
		</ul>
	</li>
	<li>
		<h1 id="childrens-beds">Childrens Beds</h1>
		<img src="/images/childrens-bed.gif" alt="Childrens Bed" width="190" height="135"/>
		<ul>
			<li><span class="name"><span class="bold">Girls Pink</span> Childrens Beds</span><span class="from from-39">From &pound;39.00</span></li>
			<li><span class="name"><span class="bold">Girls Cream</span> Childrens Beds</span><span class="from from-39">From &pound;39.00</span></li>
			<li><span class="name"><span class="bold">Soccer</span> Childrens Beds</span><span class="from from-39">From &pound;39.00</span></li>
			<li><span class="name"><span class="bold">Princess</span> Childrens Beds</span><span class="from from-69">From &pound;69.00</span></li>
			<li><span class="name"><span class="bold">Racing Car</span> Childrens Beds</span><span class="from from-99">From &pound;99.00</span></li>
		</ul>
	</li>
</ul>
<br style="clear:both;"/>
<ul class="bottom-boxes">
	<li><h1 class="memory-foam-pillows">Memory Foam Pillows</h1><img src="/images/pillow.gif" alt="Pillow" width="248" height="120" class="pillow" /><img src="/images/now-9.gif" alt="Now &pound;9.99" class="now-9" width="303" height="41" /></li>
	<li><h1 class="memory-foam-toppers">Memory Foam Toppers</h1><img src="/images/topper.gif" alt="Topper" width="237" height="47" class="topper" />
		<ul>
			<li>Single <br /><span>Memory Foam Topper</span><span class="now-59">Now &pound;59.00</span></li>
			<li>Double <br /><span>Memory Foam Topper</span><span class="now-99">Now &pound;99.00</span></li>
			<li>Kingsize <br /><span>Memory Foam Topper</span><span class="now-99">Now &pound;99.00</span></li>
			<li>Super Kingsize <br /><span>Memory Foam Topper</span><span class="now-99">Now &pound;99.00</span></li>
		</ul>
	</li>
	<li><h1 class="find-us">Find Us</h1><div id="map_canvas"></div></li>
</ul>