<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title><?php if(isset($page_title)){ echo $page_title ? $page_title : "Dirtcheapbeds.com"; } else { echo "Dirtcheapbeds.com"; }?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="<?php if(isset($meta_description)){ echo $meta_description ? $meta_description : "Dirt cheap beds available to pick up."; } else { echo "Dirt cheap beds available to pick up."; }?>" />
	<meta name="keywords" content="<?php if(isset($meta_keywords)){ echo $meta_keywords ? $meta_keywords : "cheap beds, cheap mattresses"; } else { echo "cheap beds, cheap mattresses"; }?>" />
	<link type="text/css" rel="stylesheet" href="/min/f=/css/style.css" />
	<link rel="stylesheet" href="/css/lightbox.css" type="text/css" media="screen" />
</head>
<body <?php echo str_replace("/","",$_SERVER['REQUEST_URI']) ? "class=\"" . str_replace("/","",$_SERVER['REQUEST_URI']) . "\"": "";?> onload="initialize()">
<div class="wrapper">
	<div class="header">
		<a href="/" title="Home"><img src="/images/logo.gif" alt="Dirt Cheap Beds" id="logo" width="292" height="76"/></a>
		<img src="../images/img-call-number.gif" alt="Call Our Sales Hotline 08458339223" id="call-logo" width="263" height="65"/>
	</div>